package ChatWebServer;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author w1606044
 */
public class registerPage extends javax.swing.JFrame {

    public static threadSelect tS = new threadSelect();
    public static ArrayList<loginElements> tmpArray = tS.getArray();

    /**
     * Creates new form loginPage
     */
    public registerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regPass = new javax.swing.JPasswordField();
        regPass2 = new javax.swing.JPasswordField();
        regID = new javax.swing.JTextField();
        regNickName = new javax.swing.JTextField();
        regBtn = new javax.swing.JButton();
        registerError = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Westminster Threads");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Westminster Register System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Repeat Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Login ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nickname");

        regPass.setName("text3"); // NOI18N

        regPass2.setName("text4"); // NOI18N
        regPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterBtn(evt);
            }
        });

        regID.setName("text2"); // NOI18N

        regNickName.setName("text1"); // NOI18N

        regBtn.setText("Register");
        regBtn.setName("btn1"); // NOI18N
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        registerError.setEditable(false);
        registerError.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(regPass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regNickName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addComponent(registerError)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addComponent(regPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(registerError, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        //Arranging form data into variables
        String formNickName = regNickName.getText();
        String formloginID = regID.getText();
        String formPass = new String((regPass.getPassword()));
        String formPass2 = new String((regPass2.getPassword()));

        //Nested IF statments for validation
        if (!formNickName.equals("")) {
            if (!formloginID.equals("")) {
                if (!formPass.equals("")) {
                    if (!formPass2.equals("")) {
                        if (formPass.equals(formPass2)) {
                            //Checking is username is taken
                            boolean isTaken = false;
                            for (int i = 0; i < tS.userArray.size(); i++) {
                                if (tS.userArray.get(i).loginid.equals(formloginID)) {
                                    isTaken = true;
                                }
                            }
                            if (!isTaken) {
                                //Setting new obhect and adding it onto the array for a succesful register
                                loginElements lE = new loginElements();
                                lE.setLoginid(formloginID);
                                lE.setNickname(formNickName);
                                lE.setPassword(formPass);
                                tmpArray.add(lE);
                                try {
                                    tS.setArray(tmpArray);
                                } catch (IOException ex) {
                                    Logger.getLogger(registerPage.class.getName()).log(Level.SEVERE, null, ex);
                                }

                                loginPage lP = new loginPage();
                                lP.setVisible(true);
                                super.dispose();

                                registerError.setText("Account created...");
                            } else {
                                registerError.setText("Login ID is already taken!");
                            }

                        } else {
                            registerError.setText("Both password fields need to match!");
                        }
                    } else {
                        registerError.setText("Please fill in the Password Retype field!");
                    }
                } else {
                    registerError.setText("Please fill in the the Password field!");
                }
            } else {
                registerError.setText("Please fill in the ID field!");
            }
        } else {
            registerError.setText("Please fill in the the Nick Name field!");
        }
    }//GEN-LAST:event_regBtnActionPerformed

    private void enterBtn(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterBtn
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            regBtnActionPerformed(null);
        }
    }//GEN-LAST:event_enterBtn

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton regBtn;
    private javax.swing.JTextField regID;
    private javax.swing.JTextField regNickName;
    private javax.swing.JPasswordField regPass;
    private javax.swing.JPasswordField regPass2;
    private javax.swing.JTextField registerError;
    // End of variables declaration//GEN-END:variables
}
